name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ master ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Test Security
      run: comando de teste de segurança
      env:
        DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}
    - name: Send Telegram Notification
      uses: appleboy/telegram-action@v1.3.0
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        message: Teste de segurança bem-sucedido!
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/app:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Start Docker Container
      run: docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/app:latest
    - name: Send Telegram Notification
      uses: appleboy/telegram-action@v1.3.0
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        message: Deploy bem-sucedido!
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
